name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Atualiza a cada hora
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with latest GitHub stats
        run: |
          curl -o README.md https://raw.githubusercontent.com/ntlcs/ntlcs/main/README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest GitHub stats"
          git push
